version: "3.8"

# Override any defaults specified by `${FOO:-bar}` in `.env` with `FOO=qux`.
# ${VARIABLE:-default} evaluates to default if VARIABLE is unset or empty in the environment.
# ${VARIABLE-default} evaluates to default only if VARIABLE is unset in the environment.

services:
  #  _       _
  # | |_ ___| | ___   _
  # | __/ _ \ |/ / | | |
  # | ||  __/   <| |_| |
  #  \__\___|_|\_\\__,_|

  teku_vc:
    image: consensys/teku:${TEKU_VERSION:-23.5.0}
    depends_on: [charon]
    command: |
      validator-client
      --beacon-node-api-endpoint="http://charon:3600"
      --data-base-path="/opt/data"
      --metrics-enabled=true
      --metrics-host-allowlist="*"
      --metrics-interface="0.0.0.0"
      --metrics-port="8008"
      --network="auto"
      --validator-keys="/opt/charon/validator_keys:/opt/charon/validator_keys"
      --validators-keystore-locking-enabled=false
      --validators-graffiti="Obol Distributed Validator"
      --validators-proposer-default-fee-recipient="0x0000000000000000000000000000000000000000"
    volumes:
      - ../../.charon/validator_keys:/opt/charon/validator_keys
      - ./data/teku_vc:/opt/data
    restart: unless-stopped

networks:
  default:
    name: ${CHARON_DOCKER_NETWORK:-compose_development_dvnode}
    external: true

# dc -f compose_development/execution_clients/geth.yml -f compose_development/consensus_clients/lighthouse.yml -f compose_development/charon.yml -f compose_development/validator_clients/teku.yml up -d