version: "3.8"

# Docker-compose file to trigger voluntary exits. See README.md for info.

# Override any defaults specified by `${FOO:-bar}` in `.env` with `FOO=qux`.
# See .env.sample "Voluntary Exit Config" section

services:
  teku-exit:
    image: consensys/teku:${TEKU_VERSION:-22.12.0}
    command: |
      voluntary-exit
      --beacon-node-api-endpoint="http://charon:3600"
      --confirmation-enabled=false
      --validator-keys="/opt/charon/exit_keys:/opt/charon/exit_keys"
      --epoch=${EXIT_EPOCH:-112260}
    volumes:
      - ".charon/exit_keys:/opt/charon/exit_keys"

networks:
  default:
    name: ${CHARON_DOCKER_NETWORK:-charon-distributed-validator-node_dvnode}
    external: true
