# Override any defaults specified by `${FOO:-bar}` in `.env` with `FOO=qux`.
# ${VARIABLE:-default} evaluates to default if VARIABLE is unset or empty in the environment.
# ${VARIABLE-default} evaluates to default only if VARIABLE is unset in the environment.

services:
  #                                _ _        _                     _
  #   ___ ___  _ __ ___  _ __ ___ (_) |_     | |__   ___   ___  ___| |_
  #  / __/ _ \| '_ ` _ \| '_ ` _ \| | __|____| '_ \ / _ \ / _ \/ __| __|
  # | (_| (_) | | | | | | | | | | | | ||_____| |_) | (_) | (_) \__ \ |_
  #  \___\___/|_| |_| |_|_| |_| |_|_|\__|    |_.__/ \___/ \___/|___/\__|

  mev-commitboost:
    profiles: [mev-commitboost]
    image: ghcr.io/commit-boost/pbs:${MEV_COMMITBOOST_VERSION:-v0.7.0}
    environment:
      - CB_CONFIG=/etc/commit-boost/config.toml
    volumes:
      - ./commit-boost/config.toml:/etc/commit-boost/config.toml:ro
    labels:
      - "promtail-monitored=${MEV_COMMIT_BOOST_PROMTAIL_MONITORED:-true}"
    networks: [dvnode]
    restart: unless-stopped

  #                             _                     _
  #   _ __ ___   _____   __    | |__   ___   ___  ___| |_
  #  | '_ ` _ \ / _ \ \ / /____| '_ \ / _ \ / _ \/ __| __|
  #  | | | | | |  __/\ V /_____| |_) | (_) | (_) \__ \ |_
  #  |_| |_| |_|\___| \_/      |_.__/ \___/ \___/|___/\__|

  mev-mevboost:
    profiles: [mev-mevboost]
    image: flashbots/mev-boost:${MEV_MEVBOOST_VERSION:-1.9}
    command: |
      -${NETWORK}
      -loglevel=debug
      -addr=0.0.0.0:18550
      -relay-check
      -relays=${MEV_RELAYS}
      -request-timeout-getheader=${MEV_TIMEOUT_GETHEADER:-950}
      -request-timeout-getpayload=${MEV_TIMEOUT_GETPAYLOAD:-4000}
      -request-timeout-regval=${MEV_TIMEOUT_REGVAL:-3000}
    labels:
      - "promtail-monitored=${MEV_MEV_BOOST_PROMTAIL_MONITORED:-true}"
    networks: [dvnode]
    restart: unless-stopped
