# Override any defaults specified by `${FOO:-bar}` in `.env` with `FOO=qux`.
# ${VARIABLE:-default} evaluates to default if VARIABLE is unset or empty in the environment.
# ${VARIABLE-default} evaluates to default only if VARIABLE is unset in the environment.

services:
  #             _   _                         _           _
  #  _ __   ___| |_| |__   ___ _ __ _ __ ___ (_)_ __   __| |
  # | '_ \ / _ \ __| '_ \ / _ \ '__| '_ ` _ \| | '_ \ / _` |
  # | | | |  __/ |_| | | |  __/ |  | | | | | | | | | | (_| |
  # |_| |_|\___|\__|_| |_|\___|_|  |_| |_| |_|_|_| |_|\__,_|

  el-nethermind:
    profiles: [el-nethermind]
    image: nethermind/nethermind:${EL_NETHERMIND_VERSION:-1.34.1}
    restart: unless-stopped
    ports:
      - ${EL_PORT_P2P:-30303}:30303/tcp # P2P TCP
      - ${EL_PORT_P2P:-30303}:30303/udp # P2P UDP
      - ${EL_IP_HTTP:-127.0.0.1}:${EL_PORT_HTTP:-8545}:8545 # JSON-RPC
      - ${EL_IP_ENGINE:-127.0.0.1}:${EL_PORT_ENGINE:-8551}:8551 # ENGINE-API
    labels:
      - "promtail-monitored=${EL_NETHERMIND_PROMTAIL_MONITORED:-true}"
    command: |
      --config=${NETWORK}
      --data-dir=/nethermind/data
      --HealthChecks.Enabled=true
      --JsonRpc.Enabled=true
      --JsonRpc.JwtSecretFile="/root/jwt/jwt.hex"
      --JsonRpc.EngineHost=0.0.0.0
      --JsonRpc.EnginePort=8551
      --JsonRpc.Host=0.0.0.0
      --JsonRpc.Port=8545
      --Metrics.Enabled=true
      --Metrics.ExposePort=8008
      --Sync.SnapSync=true
      --Sync.AncientBodiesBarrier=4367322
      --Sync.AncientReceiptsBarrier=4367322
    networks: [dvnode]
    volumes:
      - ./data/nethermind:/nethermind/data
      - ./jwt:/root/jwt

  #           _   _
  #  _ __ ___| |_| |__
  # | '__/ _ \ __| '_ \
  # | | |  __/ |_| | | |
  # |_|  \___|\__|_| |_|

  el-reth:
    profiles: [el-reth]
    image: ghcr.io/paradigmxyz/reth:${EL_RETH_VERSION:-v1.8.2}
    restart: unless-stopped
    ports:
      - ${EL_PORT_P2P:-30303}:30303/tcp # P2P TCP
      - ${EL_PORT_P2P:-30303}:30303/udp # P2P UDP
      - ${EL_IP_HTTP:-127.0.0.1}:${EL_PORT_HTTP:-8545}:8545 # JSON-RPC
      - ${EL_IP_ENGINE:-127.0.0.1}:${EL_PORT_ENGINE:-8551}:8551 # ENGINE-API
    labels:
      - "promtail-monitored=${EL_RETH_PROMTAIL_MONITORED:-true}"
    command: |
      node
      --chain=${NETWORK}
      --datadir=/reth/data
      --authrpc.jwtsecret="/root/jwt/jwt.hex"
      --authrpc.addr=0.0.0.0
      --authrpc.port=8551
      --http
      --http.addr=0.0.0.0
      --http.port=8545
      --metrics=0.0.0.0:8008
    networks: [dvnode]
    volumes:
      - ./data/reth:/reth/data
      - ./jwt:/root/jwt
