# Override any defaults specified by `${FOO:-bar}` in `.env` with `FOO=qux`.
# ${VARIABLE:-default} evaluates to default if VARIABLE is unset or empty in the environment.
# ${VARIABLE-default} evaluates to default only if VARIABLE is unset in the environment.

services:
  #                            _ _
  #   __ _ _ __ __ _ _ __   __| (_)_ __   ___
  #  / _` | '__/ _` | '_ \ / _` | | '_ \ / _ \
  # | (_| | | | (_| | | | | (_| | | | | |  __/
  #  \__, |_|  \__,_|_| |_|\__,_|_|_| |_|\___|
  #  |___/

  cl-grandine:
    profiles: [cl-grandine]
    image: sifrai/grandine:${GRANDINE_VERSION:-2.0.1}
    restart: unless-stopped
    labels:
      - "alloy-monitored=${CL_GRANDINE_ALLOY_MONITORED:-true}"
    command:
      - --data-dir=/root/.grandine
      - --eth1-rpc-urls=http://${EL}:8551
      - --jwt-secret=/jwt/jwt.hex
      - --http-address=0.0.0.0
      - --http-port=5052
      - --network=${NETWORK}
      - --metrics
      - --metrics-port=5054
      - --metrics-address=0.0.0.0
      - --checkpoint-sync-url=${LIGHTHOUSE_CHECKPOINT_SYNC_URL}
      - --builder-url=http://${MEV}:18550
      - --max-empty-slots=4096
    ports:
      - ${CL_PORT_P2P:-9000}:9000/tcp
      - ${CL_PORT_P2P:-9000}:9000/udp
      - ${CL_IP_HTTP:-127.0.0.1}:${CL_PORT_HTTP:-5052}:5052
    volumes:
      - ./data/cl-grandine:/root/.grandine
      - ./jwt:/jwt:ro
    networks: [dvnode]

  #  _ _       _     _   _
  # | (_) __ _| |__ | |_| |__   ___  _   _ ___  ___
  # | | |/ _` | '_ \| __| '_ \ / _ \| | | / __|/ _ \
  # | | | (_| | | | | |_| | | | (_) | |_| \__ \  __/
  # |_|_|\__, |_| |_|\__|_| |_|\___/ \__,_|___/\___|
  #      |___/

  cl-lighthouse:
    profiles: [cl-lighthouse]
    image: sigp/lighthouse:${LIGHTHOUSE_VERSION:-v8.1.0}
    restart: unless-stopped
    labels:
      - "alloy-monitored=${CL_LIGHTHOUSE_ALLOY_MONITORED:-true}"
    command: |
      lighthouse bn
      --network=${NETWORK}
      --checkpoint-sync-url=${LIGHTHOUSE_CHECKPOINT_SYNC_URL}
      --checkpoint-sync-url-timeout=600
      --execution-endpoint=http://${EL}:8551
      --execution-jwt=/opt/jwt/jwt.hex
      --datadir=/opt/app/beacon/
      --builder=http://${MEV}:18550
      --http
      --http-address=0.0.0.0
      --http-port=5052
      --metrics
      --metrics-address=0.0.0.0
      --metrics-port=5054
      --metrics-allow-origin="*"
    ports:
      - ${CL_PORT_P2P:-9000}:9000/tcp
      - ${CL_PORT_P2P:-9000}:9000/udp
      - ${CL_IP_HTTP:-127.0.0.1}:${CL_PORT_HTTP:-5052}:5052
    volumes:
      - ./data/lighthouse:/opt/app/beacon # Keep data in lighthouse and not cl-lighthouse for backwards compatibility
      - ./jwt:/opt/jwt
    networks: [dvnode]

  #  _       _
  # | |_ ___| | ___   _
  # | __/ _ \ |/ / | | |
  # | ||  __/   <| |_| |
  #  \__\___|_|\_\\__,_|

  cl-teku:
    profiles: [cl-teku]
    image: consensys/teku:${CL_TEKU_VERSION:-26.2.0}
    restart: unless-stopped
    labels:
      - "alloy-monitored=${CL_TEKU_ALLOY_MONITORED:-true}"
    command: |
      --network=${NETWORK}
      --checkpoint-sync-url=${LIGHTHOUSE_CHECKPOINT_SYNC_URL}
      --ee-endpoint=http://${EL}:8551
      --ee-jwt-secret-file=/jwt/jwt.hex
      --data-base-path=/opt/teku/data
      --builder-endpoint=http://${MEV}:18550
      --rest-api-enabled=true
      --rest-api-interface=0.0.0.0
      --rest-api-port=5052
      --rest-api-host-allowlist="*"
      --metrics-enabled=true
      --metrics-interface=0.0.0.0
      --metrics-port=5054
      --metrics-host-allowlist="*"
    ports:
      - ${CL_PORT_P2P:-9000}:9000/tcp
      - ${CL_PORT_P2P:-9000}:9000/udp
      - ${CL_IP_HTTP:-127.0.0.1}:${CL_PORT_HTTP:-5052}:5052
    volumes:
      - ./data/cl-teku:/opt/teku/data
      - ./jwt:/jwt:ro
    networks: [dvnode]

  #  _           _           _
  # | | ___   __| | ___  ___| |_ __ _ _ __
  # | |/ _ \ / _` |/ _ \/ __| __/ _` | '__|
  # | | (_) | (_| |  __/\__ \ || (_| | |
  # |_|\___/ \__,_|\___||___/\__\__,_|_|

  cl-lodestar:
    profiles: [cl-lodestar]
    image: chainsafe/lodestar:${CL_LODESTAR_VERSION:-v1.40.0}
    restart: unless-stopped
    labels:
      - "alloy-monitored=${CL_LODESTAR_ALLOY_MONITORED:-true}"
    command: |
      beacon
      --network=${NETWORK}
      --checkpointSyncUrl=${LIGHTHOUSE_CHECKPOINT_SYNC_URL}
      --execution.urls=http://${EL}:8551
      --jwt-secret=/jwt/jwt.hex
      --dataDir=/opt/lodestar/data
      --builder
      --builder.url=http://${MEV}:18550
      --rest
      --rest.address=0.0.0.0
      --rest.port=5052
      --metrics
      --metrics.address=0.0.0.0
      --metrics.port=5054
    ports:
      - ${CL_PORT_P2P:-9000}:9000/tcp
      - ${CL_PORT_P2P:-9000}:9000/udp
      - ${CL_IP_HTTP:-127.0.0.1}:${CL_PORT_HTTP:-5052}:5052
    volumes:
      - ./data/cl-lodestar:/opt/lodestar/data
      - ./jwt:/jwt:ro
    networks: [dvnode]
