services:
  alloy:
    image: grafana/alloy:${ALLOY_VERSION:-v1.11.3}
    environment:
      CHARON_LOKI_ADDRESSES: ${CHARON_LOKI_ADDRESSES}
      CLUSTER_NAME: ${CLUSTER_NAME}
      CLUSTER_PEER: ${CLUSTER_PEER}
    volumes:
      - ./alloy:/etc/alloy
      - /var/run/docker.sock:/var/run/docker.sock
    networks: [dvnode]
    entrypoint: /etc/alloy/run.sh
    command: ["/bin/alloy", "run", "/etc/alloy/config.alloy", "--storage.path=/var/lib/alloy/data"]
    restart: unless-stopped

networks:
  dvnode:
