version: "3.8"

# Docker-compose file to run mev-boost (https://boost.flashbots.net/).
# To run the compose stack with mev-boost, run `docker-compose -f docker-compose.yml -f mevboost-compose.yml up`.
# We use public relays from https://research.lido.fi/t/lido-on-ethereum-call-for-relay-providers/2844.

# Override any defaults specified by `${FOO:-bar}` in `.env` with `FOO=qux`.

services:
  #      _                     _
  #  _ __ ___   _____   __    | |__   ___   ___  ___| |_
  #  | '_ ` _ \ / _ \ \ / /____| '_ \ / _ \ / _ \/ __| __|
  #  | | | | | |  __/\ V /_____| |_) | (_) | (_) \__ \ |_
  #  |_| |_| |_|\___| \_/      |_.__/ \___/ \___/|___/\__|
  mev-boost:
    image: flashbots/mev-boost:${MEVBOOST_VERSION:-1.5.0}
    command: |
      -${NETWORK:-goerli} 
      -loglevel=debug
      -addr=0.0.0.0:18550
      -relay-check
      -relays=${MEVBOOST_RELAYS:-"https://0x8f7b17a74569b7a57e9bdafd2e159380759f5dc3ccbd4bf600414147e8c4e1dc6ebada83c0139ac15850eb6c975e82d0@builder-relay-goerli.blocknative.com,https://0xafa4c6985aa049fb79dd37010438cfebeb0f2bd42b115b89dd678dab0670c1de38da0c4e9138c9290a398ecd9a0b3110@boost-relay-goerli.flashbots.net"}
    restart: unless-stopped

networks:
  default:
    name: ${CHARON_DOCKER_NETWORK:-charon-distributed-validator-node_dvnode}
    external: true