version: "3.8"

# Override any defaults specified by `${FOO:-bar}` in `.env` with `FOO=qux`.
# ${VARIABLE:-default} evaluates to default if VARIABLE is unset or empty in the environment.
# ${VARIABLE-default} evaluates to default only if VARIABLE is unset in the environment.

services:
  #  _ _       _     _   _
  # | (_) __ _| |__ | |_| |__   ___  _   _ ___  ___
  # | | |/ _` | '_ \| __| '_ \ / _ \| | | / __|/ _ \
  # | | | (_| | | | | |_| | | | (_) | |_| \__ \  __/
  # |_|_|\__, |_| |_|\__|_| |_|\___/ \__,_|___/\___|
  #      |___/

  lighthouse_bn:
    image: sigp/lighthouse:${LIGHTHOUSE_VERSION:-v4.1.0}
    ports:
      - ${LIGHTHOUSE_PORT_P2P:-9000}:9000/tcp   # P2P TCP
      - ${LIGHTHOUSE_PORT_P2P:-9000}:9000/udp   # P2P UDP
    command: |
      lighthouse bn
      --network=${NETWORK:-goerli}
      --checkpoint-sync-url=${LIGHTHOUSE_CHECKPOINT_SYNC_URL:-https://checkpoint-sync.goerli.ethpandaops.io}
      --execution-endpoint=http://geth:8551
      --execution-jwt=/opt/jwt/jwt.hex
      --datadir=/opt/app/beacon/
      --builder=http://mev-boost:18550
      --http
      --http-address=0.0.0.0
      --http-port=5052
      --metrics
      --metrics-address=0.0.0.0
      --metrics-port=5054
      --metrics-allow-origin="*"
    volumes:
      - ../data/lighthouse_bn:/opt/app/beacon
      - ../../jwt:/opt/jwt
    restart: unless-stopped

networks:
  default:
    name: ${CHARON_DOCKER_NETWORK:-compose_development_dvnode}
    external: true
