{
 "title": "Local Docker Cluster Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Peer Latency Observed by Charon 0",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "p2p_ping_latency_secs_sum{job=\"charon-0\"} / p2p_ping_latency_secs_count",
     "legendFormat": "{{job}}-{{peer}}"
    }
   ]
  },
  {
   "title": "Peer Latency Observed by Charon 1",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "p2p_ping_latency_secs_sum{job=\"charon-1\"} / p2p_ping_latency_secs_count",
     "legendFormat": "{{job}}-{{peer}}"
    }
   ]
  },
  {
   "title": "Peer Latency Observed by Charon 2",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "p2p_ping_latency_secs_sum{job=\"charon-2\"} / p2p_ping_latency_secs_count",
     "legendFormat": "{{job}}-{{peer}}"
    }
   ]
  },
  {
   "title": "Peer Latency Observed by Charon 3",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "p2p_ping_latency_secs_sum{job=\"charon-3\"} / p2p_ping_latency_secs_count",
     "legendFormat": "{{job}}-{{peer}}"
    }
   ]
  },
  {
   "title": "Node start time",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    { "expr": "app_start_time_secs * 1000", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Latest Slot",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    { "expr": "core_scheduler_current_slot", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Beacon Node Latency",
   "type": "graph",
   "description": "Total request length / Total number of requests made to beacon nodes by charon clients",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short", "label": "Seconds" }
   ],
   "targets": [
    {
     "expr": "app_eth2_latency_seconds_sum / app_eth2_latency_seconds_count",
     "legendFormat": "{{job}}-{{endpoint}}"
    }
   ]
  },
  {
   "title": "Ping Errors between clients in the last 5 minutes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rate(p2p_ping_error_total[5m])" }
   ]
  }
 ]
}