{
 "title": "Single Charon Node Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Beacon Client", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "LIGHTHOUSE",
   "type": "stat",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "1" }
   ]
  },
  {
   "title": "Syncing chain counts",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "sync_range_chains", "legendFormat": "{{range_type}}" }
   ]
  },
  {
   "title": "Current Slot",
   "type": "stat",
   "description": "Lighthouse's reported current slot (unsafe not finalised)",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "max(slotclock_present_slot)" }
   ]
  },
  {
   "title": "Peer Sync Status",
   "type": "piechart",
   "description": "The sync status for lighthouse's peers",
   "gridPos": { "h": 5, "w": 4, "x": 9, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sync_peers_per_status", "legendFormat": "{{sync_status}}" }
   ]
  },
  {
   "title": "Peer Type",
   "type": "piechart",
   "description": "Peers that have dialed us. Indicates if our node is reachable",
   "gridPos": { "h": 5, "w": 4, "x": 13, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "network_inbound_peers", "legendFormat": "Inbound" },
    { "expr": "network_outbound_peers", "legendFormat": "Outbound" }
   ]
  },
  {
   "title": "Eth1 Execution Client Connected",
   "type": "stat",
   "description": "Identifies if there is an upstream execution client connected",
   "gridPos": { "h": 4, "w": 4, "x": 17, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "sync_eth1_connected", "legendFormat": "{{range_type}}" }
   ]
  },
  {
   "title": "Eth2 Consensus Client Synced",
   "type": "stat",
   "description": "Identifies if the consensus client is synced",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "sync_eth2_synced", "legendFormat": "{{range_type}}" }
   ]
  },
  { "title": "Charon", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "CHARON",
   "type": "stat",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "1" }
   ]
  },
  {
   "title": "Version Info",
   "type": "table",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "(\n  sum(app_git_commit) by (git_hash)\n)\n   + on(job) group_left(version)\n(\n   0 * sum(app_version) by (version)\n)\n   + on(job) group_left(lock_hash)\n(\n   0 * sum(app_lock_hash) by (lock_hash)\n)"
    }
   ]
  },
  {
   "title": "Charon Status",
   "type": "stat",
   "description": "Is charon connected to a synced beacon client and a threshold of peers?",
   "gridPos": { "h": 4, "w": 4, "x": 6, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "app_monitoring_readyz" }
   ]
  },
  {
   "title": "Running Since",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 10, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "(time() - app_start_time_secs)", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Current Slot",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 13, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "core_scheduler_current_slot", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "P2P Reachability",
   "type": "stat",
   "description": "Current libp2p reachability status of this node as detected by AutoNat.",
   "gridPos": { "h": 4, "w": 3, "x": 17, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "p2p_reachability_status" }
   ]
  },
  {
   "title": "Number of connected peers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(p2p_ping_success)" }
   ]
  },
  {
   "title": "Number of participating peers",
   "type": "stat",
   "gridPos": { "h": 10, "w": 10, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(core_tracker_participation{job=\"charon\"}) by (duty)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Peer ping latency (90%)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 10, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(p2p_ping_latency_secs_bucket[30s])) by (le,peer))  ",
     "legendFormat": "{{peer}}"
    }
   ]
  },
  {
   "title": "Attestations Submitted",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "core_bcast_broadcast_total{duty=\"attester\"}",
     "legendFormat": "{{duty}}"
    }
   ]
  },
  {
   "title": "Blocks Proposed",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "core_bcast_broadcast_total{duty=\"proposer\"}"
    }
   ]
  },
  {
   "title": "Beacon Node Latency (90%)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(app_eth2_latency_seconds_bucket[30s])) by (le,endpoint)) ",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "description": "Host machine's memory usage",
   "gridPos": { "h": 9, "w": 9, "x": 8, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes - node_memory_MemFree_bytes - node_memory_Buffers_bytes - node_memory_Cached_bytes - node_memory_SwapCached_bytes - node_memory_Slab_bytes - node_memory_PageTables_bytes - node_memory_VmallocUsed_bytes",
     "legendFormat": "apps"
    },
    { "expr": "node_memory_Buffers_bytes", "legendFormat": "buffers" },
    { "expr": "node_memory_Cached_bytes", "legendFormat": "cached" },
    { "expr": "node_memory_MemFree_bytes", "legendFormat": "free" },
    { "expr": "node_memory_Slab_bytes", "legendFormat": "slab" }
   ]
  },
  { "title": "Validator", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "TEKU",
   "type": "stat",
   "description": "A teku validator client serving as part of this distributed validator cluster",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "1", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Number of validators",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "validator_local_validator_count"
    }
   ]
  },
  {
   "title": "Current Epoch",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "validator_current_epoch" }
   ]
  },
  {
   "title": "Attestations Published",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "validator_beacon_node_published_attestation_total"
    }
   ]
  },
  {
   "title": "Blocks Proposed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "validator_beacon_node_published_block_total"
    }
   ]
  },
  {
   "title": "Validator Statuses",
   "type": "table",
   "description": "Number of Validators with the given status.",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "validator_local_validator_counts > 0",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Duties Failed",
   "type": "timeseries",
   "description": "Counters of each duty failed  by this cluster, separated by duty type",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 38 },
   "targets": [
    {
     "expr": "increase(validator_duties_performed{result=\"failed\"}[$__rate_interval])",
     "legendFormat": "{{type}}"
    }
   ]
  }
 ]
}