{
 "title": "Single Charon Node View - User Mode",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "cluster_network",
    "label": "Cluster Network",
    "query": {
     "query": "label_values(app_peerinfo_nickname,cluster_network)"
    }
   },
   {
    "name": "cluster_name",
    "label": "Cluster Name",
    "query": {
     "query": "label_values(app_peerinfo_nickname{cluster_network=~\"$cluster_network\"},cluster_name)"
    }
   },
   {
    "name": "cluster_hash",
    "label": "Cluster Hash",
    "query": {
     "query": "label_values(app_peerinfo_nickname{cluster_name=\"$cluster_name\"},cluster_hash)"
    }
   },
   {
    "name": "cluster_peer",
    "label": "Cluster Peer",
    "query": {
     "query": "label_values(app_peerinfo_nickname{cluster_name=\"$cluster_name\", cluster_hash=\"$cluster_hash\"},cluster_peer)"
    }
   },
   {
    "name": "duty",
    "label": "Duty",
    "query": "attester,prepare_aggregator,aggregator,sync_message,prepare_sync_contribution,sync_contribution,proposer,randao,exit,builder_proposer,builder_registration,info_sync"
   },
   {
    "name": "interval",
    "label": "Interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Health Status",
   "type": "stat",
   "description": "Status returned from the `/readyz` health status endpoint. Unhealthy reasons include beacon node problems, charon p2p problems, or validator client problems.",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "app_monitoring_readyz{cluster_name=\"$cluster_name\",cluster_hash=\"$cluster_hash\",cluster_peer=\"$cluster_peer\"}"
    }
   ]
  },
  {
   "title": "Current Status",
   "type": "stat",
   "description": "- **Uptime**: Total time since cluster start time\n- **Slot**: Current slot\n- **Epoch**: Current Epoch\n- **Validators Active**: Number of active validators in the cluster\n- **Charon Peers Connected**: Number of Peers in the cluster\n- **Relays Connected**: Number of Relays connected to the cluster\n- **Beacon Node Peers**: Beacon Node Peers connected, based on app_beacon_node_peers\n- **P2P Reachability**\" Latest P2P reachability status, based on p2p_reachability_status",
   "gridPos": { "h": 9, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "core_scheduler_current_slot{cluster_name=\"$cluster_name\",cluster_hash=\"$cluster_hash\",cluster_peer=\"$cluster_peer\"}",
     "legendFormat": "Slot"
    },
    {
     "expr": "core_scheduler_current_epoch{cluster_name=\"$cluster_name\",cluster_hash=\"$cluster_hash\",cluster_peer=\"$cluster_peer\"}",
     "legendFormat": "Epoch"
    },
    {
     "expr": "core_scheduler_validators_active{cluster_name=\"$cluster_name\",cluster_hash=\"$cluster_hash\",cluster_peer=\"$cluster_peer\"}",
     "legendFormat": "Validators Active"
    },
    {
     "expr": "sum(p2p_ping_success{cluster_name=\"$cluster_name\",cluster_hash=\"$cluster_hash\",cluster_peer=\"$cluster_peer\"})",
     "legendFormat": "Charon Peers Connected"
    },
    {
     "expr": "sum(p2p_relay_connections{cluster_name=\"$cluster_name\",cluster_hash=\"$cluster_hash\",cluster_peer=\"$cluster_peer\"}) ",
     "legendFormat": "Relays Connected"
    },
    {
     "expr": "app_beacon_node_peers{cluster_name=\"$cluster_name\",cluster_hash=\"$cluster_hash\",cluster_peer=\"$cluster_peer\"}",
     "legendFormat": "Beacon Node Peers"
    },
    {
     "expr": "p2p_reachability_status{cluster_name=\"$cluster_name\",cluster_hash=\"$cluster_hash\",cluster_peer=\"$cluster_peer\"}",
     "legendFormat": "P2P Reachability"
    }
   ]
  },
  {
   "title": "Peer Duty Success(%) ",
   "type": "gauge",
   "description": "Successful cluster duty percentage by type over the whole time range. This metric uses the reporting node's view of the chain, and may not be completely accurate (for example if its peers succeed with the duty without this node taking part), consult a block explorer for a more definitive success rate. ",
   "gridPos": { "h": 9, "w": 16, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  sum(increase(core_tracker_success_duties_total{\n    cluster_name=\"$cluster_name\",\n    cluster_hash=\"$cluster_hash\",\n    cluster_peer=~\"$cluster_peer\",\n    duty=~\"attester|proposer|sync_message\"\n  }[$__range])) \n  by (duty)\n)\n/\n(\n  sum(increase(core_tracker_expect_duties_total{\n    cluster_name=\"$cluster_name\",\n    cluster_hash=\"$cluster_hash\",\n    cluster_peer=~\"$cluster_peer\",\n    duty=~\"attester|proposer|sync_message\"\n  }[$__range])) \n  by (duty)\n) > 0 ",
     "legendFormat": "{{duty}}"
    }
   ]
  },
  {
   "title": "Cluster Info",
   "type": "stat",
   "description": "Information about the charon cluster.\n\n- **Network**: The blockchain network \n- **Operators/Nodes**: The number of operators or nodes or peers in the charon DV cluster.\n- **Threshold**: The minimum number of participating nodes (also quorum).\n- **Validators**: The number of validators added to the cluster, each validator is staking 32 ETH. ",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "( 1 * app_version{cluster_name=\"$cluster_name\",cluster_hash=\"$cluster_hash\",cluster_peer=\"$cluster_peer\", cluster_network=\"mainnet\"} )\nor \n( 2 * app_version{cluster_name=\"$cluster_name\",cluster_hash=\"$cluster_hash\",cluster_peer=\"$cluster_peer\", cluster_network=\"goerli\"} )\nor\n( 3 * app_version{cluster_name=\"$cluster_name\",cluster_hash=\"$cluster_hash\",cluster_peer=\"$cluster_peer\", cluster_network=\"sepolia\"} )\nor\n( 4 * app_version{cluster_name=\"$cluster_name\",cluster_hash=\"$cluster_hash\",cluster_peer=\"$cluster_peer\", cluster_network=\"gnosis\"} )",
     "legendFormat": "Network"
    },
    {
     "expr": "cluster_operators{cluster_name=\"$cluster_name\",cluster_hash=\"$cluster_hash\",cluster_peer=\"$cluster_peer\"}",
     "legendFormat": "Operators/Nodes"
    },
    {
     "expr": "cluster_threshold{cluster_name=\"$cluster_name\",cluster_hash=\"$cluster_hash\",cluster_peer=\"$cluster_peer\"}",
     "legendFormat": "Threshold"
    },
    {
     "expr": "core_scheduler_validators_active{cluster_name=\"$cluster_name\",cluster_hash=\"$cluster_hash\",cluster_peer=\"$cluster_peer\"}",
     "legendFormat": "Validators Active"
    },
    {
     "expr": "cluster_validators{cluster_name=\"$cluster_name\",cluster_hash=\"$cluster_hash\",cluster_peer=\"$cluster_peer\"}",
     "legendFormat": "Validators Total"
    }
   ]
  },
  {
   "title": "Peer Connectivity and Missed Duties (🚧)",
   "type": "table",
   "description": "- **Peer**: The peer's name (inferred from their *charon-enr-private-key*)\n- **You**: ⭐️ is this local charon node\n- **Connected**: Whether you are currently connected to this peer.\n- **Direct**: Whether the connection is *direct* (👍) or *relay* (👎) \n- **Latency**: The time messages take to travel to/from the peer.\n- **Version**: The version of the peer's charon node\n- **Supported**: Whether the peers charon version is supported/compatible or not.\n- **Uptime**\" The duration since peer was restarted.\n- **🚧Attest**: Number of attestation duties missed in the time window.\n- **🚧Propose**: Number of block proposal duties missed in the time window.\n- **🚧Other**: Number of other duties missed in the time window.\n\n",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum(p2p_ping_success{cluster_name=\"$cluster_name\",cluster_hash=\"$cluster_hash\",cluster_peer=\"$cluster_peer\"}) by (peer)"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(p2p_ping_latency_secs_bucket{cluster_name=\"$cluster_name\",cluster_hash=\"$cluster_hash\",cluster_peer=\"$cluster_peer\"}[$__rate_interval])) by (le,peer))  * 1000"
    },
    {
     "expr": "sum(p2p_ping_success{cluster_name=\"$cluster_name\",cluster_hash=\"$cluster_hash\",cluster_peer=\"$cluster_peer\"}) by (peer)"
    },
    {
     "expr": "(max(p2p_peer_connection_types{cluster_name=\"$cluster_name\",cluster_hash=\"$cluster_hash\",cluster_peer=\"$cluster_peer\",type=\"direct\"}) by (peer)*10 + \nmax(p2p_peer_connection_types{cluster_name=\"$cluster_name\",cluster_hash=\"$cluster_hash\",cluster_peer=\"$cluster_peer\",type=\"relay\"}) by (peer))"
    },
    {
     "expr": "sum(app_peerinfo_version{cluster_name=\"$cluster_name\",cluster_hash=\"$cluster_hash\",cluster_peer=\"$cluster_peer\"}) by (peer,version) ",
     "legendFormat": "__auto"
    },
    {
     "expr": "time() - max(app_peerinfo_start_time_secs{cluster_name=\"$cluster_name\",cluster_hash=\"$cluster_hash\",cluster_peer=\"$cluster_peer\"} > 0) by (peer)"
    },
    {
     "expr": "max(app_peerinfo_index{cluster_name=\"$cluster_name\",cluster_hash=\"$cluster_hash\",cluster_peer=\"$cluster_peer\"}) by (peer)"
    },
    {
     "expr": "(\n    sum(increase(core_tracker_participation_missed_total{cluster_name=\"$cluster_name\",cluster_hash=\"$cluster_hash\",cluster_peer=\"$cluster_peer\", duty=\"attester\"}[$__range])) by (peer) \n/\n    sum(increase(core_tracker_participation_expected_total{cluster_name=\"$cluster_name\",cluster_hash=\"$cluster_hash\",cluster_peer=\"$cluster_peer\", duty=\"attester\"}[$__range])) by (peer) \n) OR on() vector(0)",
     "legendFormat": "__auto"
    },
    {
     "expr": "(\n    sum(increase(core_tracker_participation_missed_total{cluster_name=\"$cluster_name\",cluster_hash=\"$cluster_hash\",cluster_peer=\"$cluster_peer\", duty=~\"proposer\"}[$__range])) by (peer) \n/\n    sum(increase(core_tracker_participation_expected_total{cluster_name=\"$cluster_name\",cluster_hash=\"$cluster_hash\",cluster_peer=\"$cluster_peer\", duty=~\"proposer\"}[$__range])) by (peer) \n) OR on() vector(0)",
     "legendFormat": "__auto"
    },
    {
     "expr": "(\n    sum(increase(core_tracker_participation_missed_total{cluster_name=\"$cluster_name\",cluster_hash=\"$cluster_hash\",cluster_peer=\"$cluster_peer\", duty=\"sync_message\"}[$__range])) by (peer) \n/\n    sum(increase(core_tracker_participation_expected_total{cluster_name=\"$cluster_name\",cluster_hash=\"$cluster_hash\",cluster_peer=\"$cluster_peer\", duty=\"sync_message\"}[$__range])) by (peer) \n) OR on() vector(0)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max(app_peerinfo_version_support{cluster_name=\"$cluster_name\",cluster_hash=\"$cluster_hash\",cluster_peer=\"$cluster_peer\"}) by (peer) "
    },
    {
     "expr": "max(app_peerinfo_builder_api_enabled{cluster_name=\"$cluster_name\",cluster_hash=\"$cluster_hash\",cluster_peer=\"$cluster_peer\"}) by (peer)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(app_peerinfo_nickname{cluster_name=\"$cluster_name\",cluster_hash=\"$cluster_hash\",cluster_peer=\"$cluster_peer\"}) by (peer,peer_nickname)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max(app_beacon_node_version{cluster_name=~\"$cluster_name\",cluster_hash=~\"$cluster_hash\",cluster_network=~\"$cluster_network\"}) by (cluster_peer, version)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Historical Health Status",
   "type": "timeseries",
   "description": "Status returned from the `/readyz` health status endpoint. Unhealthy reasons include beacon node problems, charon p2p problems, or validator client problems.",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max(app_monitoring_readyz{cluster_name=\"$cluster_name\",cluster_hash=\"$cluster_hash\",cluster_peer=\"$cluster_peer\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Versions and Git Hashes",
   "type": "state-timeline",
   "description": "The running Charon's version and git commit hash",
   "gridPos": { "h": 6, "w": 7, "x": 7, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max(app_version{cluster_name=\"$cluster_name\",cluster_hash=\"$cluster_hash\",cluster_peer=\"$cluster_peer\"}) by (version)",
     "legendFormat": "{{version}}"
    },
    {
     "expr": "max(app_git_commit{cluster_name=\"$cluster_name\",cluster_hash=\"$cluster_hash\",cluster_peer=\"$cluster_peer\"}) by (git_hash)",
     "legendFormat": "{{git_hash}}"
    },
    {
     "expr": "rate(app_start_time_secs{cluster_name=\"$cluster_name\",cluster_hash=\"$cluster_hash\",cluster_peer=\"$cluster_peer\"}) > 0",
     "legendFormat": "Restarts"
    }
   ]
  },
  {
   "title": "Peer Connections (🟢=direct, 🟡=relay, 🔴=not connected)",
   "type": "state-timeline",
   "description": "Type of connections to each peer in the cluster during the time window:\n - 🟢 Green: Direct connection (this is the preferred)\n - 🟡 Yellow: Indirect relay connection (this is ok if only temporary)\n - 🔴 Red: No connection to peer (this is a problem)\n\nSee https://docs.obol.tech/docs/charon/networking#external-p2p-network",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 19 },
   "targets": [
    {
     "expr": "(max(p2p_ping_success{cluster_name=\"$cluster_name\",cluster_hash=\"$cluster_hash\",cluster_peer=\"$cluster_peer\"}) by (peer))\n+\n(1 * max(p2p_peer_connection_types{cluster_name=\"$cluster_name\",cluster_hash=\"$cluster_hash\",cluster_peer=\"$cluster_peer\",type=\"relay\"}) by (peer))\n+ \n(100 * max(p2p_peer_connection_types{cluster_name=\"$cluster_name\",cluster_hash=\"$cluster_hash\",cluster_peer=\"$cluster_peer\",type=\"direct\"}) by (peer))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failing Health Checks",
   "type": "table",
   "description": "This panels shows any health checks that are failing. See <add link> for help troubleshooting.  \n\nNote the different severities:\n- **info**: Only informational, might not be an actual problem.\n- **warning**: Performance is degraded, operator intervention only required if this persists for a long time.\n- **critical**: Significant problem, validators probably not operation at all. Immediate operator intervention required.\n \n\n",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "sum(app_health_checks{cluster_name=\"$cluster_name\",cluster_hash=\"$cluster_hash\",cluster_peer=\"$cluster_peer\"}) by (name,severity) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Validators",
   "type": "table",
   "description": "Status and balance of each validator by public key with links to beaconcha.in.\n\nIf present, the \"❗️Peer Exits\" column indicate the number of peers that submitted partially signed exits for each validator.",
   "gridPos": { "h": 8, "w": 9, "x": 8, "y": 25 },
   "targets": [
    {
     "expr": "max(core_scheduler_validator_balance_gwei{cluster_name=\"$cluster_name\",cluster_hash=\"$cluster_hash\",cluster_peer=\"$cluster_peer\"} / 1000000000) by (pubkey_full,pubkey, cluster_network)",
     "legendFormat": "{{pubkey}}"
    },
    {
     "expr": "max(core_scheduler_validator_status{cluster_name=\"$cluster_name\",cluster_hash=\"$cluster_hash\",cluster_peer=\"$cluster_peer\"} == 1) by (pubkey, status)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max(core_parsigdb_exit_total{cluster_name=\"$cluster_name\",cluster_hash=\"$cluster_hash\",cluster_peer=\"$cluster_peer\"}) by (pubkey) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Beacon Node Version",
   "type": "table",
   "description": "Number of charon nodes running particular consensus client versions",
   "gridPos": { "h": 4, "w": 7, "x": 17, "y": 25 },
   "targets": [
    {
     "expr": "max(app_beacon_node_version{cluster_name=~\"$cluster_name\",cluster_hash=~\"$cluster_hash\",cluster_network=~\"$cluster_network\", cluster_peer=~\"$cluster_peer\"}) by (cluster_name, cluster_hash, cluster_peer, version, nickname)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Validator Client Version",
   "type": "table",
   "gridPos": { "h": 4, "w": 7, "x": 17, "y": 29 },
   "targets": [
    {
     "expr": "count(core_validatorapi_vc_user_agent{cluster_name=~\"$cluster_name\",cluster_hash=~\"$cluster_hash\",cluster_network=~\"$cluster_network\", cluster_peer=~\"$cluster_peer\"}) by (cluster_peer, user_agent, nickname)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Duties", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "✅ Completed duties by type ",
   "type": "status-history",
   "description": "Completed duties by type over time.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "sum(increase(core_bcast_broadcast_total{cluster_name=\"$cluster_name\",cluster_hash=\"$cluster_hash\",cluster_peer=\"$cluster_peer\"}[$interval])) by (duty) > 0",
     "legendFormat": "{{duty}}"
    }
   ]
  },
  {
   "title": "❌ Failed duty percentage by type (per $interval)",
   "type": "timeseries",
   "description": "Failed duties percentage by type over time",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(\n    sum(increase(core_tracker_failed_duties_total{cluster_name=\"$cluster_name\",cluster_hash=\"$cluster_hash\",cluster_peer=\"$cluster_peer\"}[$interval])) by (duty)\n) \n/ \n(\n    sum(increase(core_tracker_failed_duties_total{cluster_name=\"$cluster_name\",cluster_hash=\"$cluster_hash\",cluster_peer=\"$cluster_peer\"}[$interval])) by (duty) \n    + \n    sum(increase(core_bcast_broadcast_total{cluster_name=\"$cluster_name\",cluster_hash=\"$cluster_hash\",cluster_peer=\"$cluster_peer\"}[$interval])) by (duty) \n) > 0 ",
     "legendFormat": "{{duty}}"
    }
   ]
  },
  {
   "title": "❌ Failed duties by type (per $interval)",
   "type": "status-history",
   "description": "Failed duties by type over time. Use data link to show logs.\nProposer duties are non-failing after being successfully included on-chain.\nOther broadcasted to the beacon node duties (i.e.: attester), are non-failing after being successfully broadcasted.\nAny other duties not broadcasted to the beacon node (i.e.: randao), are non-failing after consensus is reached.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "sum(increase(core_tracker_failed_duties_total{cluster_name=\"$cluster_name\",cluster_hash=\"$cluster_hash\",cluster_peer=\"$cluster_peer\"}[$interval])) by (duty) > 0",
     "legendFormat": "{{duty}}"
    }
   ]
  },
  {
   "title": "⚠️ MEV Relay Submit Registrations Failure Growth by Operator",
   "type": "timeseries",
   "description": "Which operators are having a growing number of relay registrations failures, indicating there may be a risk to an upcoming MEV block production opportunity. Be conscious that absence of an operator from this list may mean their MEV registration is working, or it may mean it is not enabled at all and thus not failing. ",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max(increase(app_eth2_errors_total{endpoint=~\"submit_validator_registrations\", cluster_name=~\"$cluster_name\"}[$__range])) by (cluster_peer, cluster_name)",
     "legendFormat": "{{cluster_name}}: {{cluster_peer}}"
    }
   ]
  },
  {
   "title": "Consensus Rounds: $duty",
   "type": "timeseries",
   "description": "The number of consensus rounds it takes to achieve consensus on a batch of duties. When every node is online, this should be 1 round, if it is taking more rounds than the fault tolerance of the cluster to come to consensus, there may be an issue with node operators in the cluster, or the latency of the cluster. ",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 46 },
   "targets": [
    {
     "expr": "max(core_consensus_decided_rounds{cluster_name=\"$cluster_name\",cluster_hash=\"$cluster_hash\",cluster_peer=\"$cluster_peer\",duty=~\"$duty\"}) by (timer, duty)",
     "legendFormat": "{{duty}}"
    }
   ]
  },
  {
   "title": "Consensus duration: $duty",
   "type": "timeseries",
   "description": "How long in total did it take to come to consensus on this/these duties? Duties generally have a 4 second window to be completed (1.25s on gnosis chain), so consensus should not take more than half of that time for good performance. ",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(core_consensus_duration_seconds_sum{cluster_name=\"$cluster_name\",cluster_hash=\"$cluster_hash\",cluster_peer=\"$cluster_peer\",duty=~\"$duty\"}[$interval]) / rate(core_consensus_duration_seconds_count{cluster_name=\"$cluster_name\",cluster_hash=\"$cluster_hash\",cluster_peer=\"$cluster_peer\",duty=~\"$duty\"}[$interval])",
     "legendFormat": "{{duty}}"
    }
   ]
  }
 ]
}