version: "3.8"

# Override any defaults specified by `${FOO:-bar}` in `.env` with `FOO=qux`.
# ${VARIABLE:-default} evaluates to default if VARIABLE is unset or empty in the environment.
# ${VARIABLE-default} evaluates to default only if VARIABLE is unset in the environment.

services:
  #             _   _
  #   __ _  ___| |_| |__
  #  / _` |/ _ \ __| '_ \
  # | (_| |  __/ |_| | | |
  #  \__, |\___|\__|_| |_|
  #  |___/

  geth:
    image: ethereum/client-go:${GETH_VERSION:-v1.11.5}
    ports:
      - ${GETH_PORT_P2P:-30303}:30303/tcp # P2P TCP
      - ${GETH_PORT_P2P:-30303}:30303/udp # P2P UDP
    command: |
      --${NETWORK:-goerli}
      --http
      --http.addr=0.0.0.0
      --http.port=8545
      --http.vhosts="*"
      --http.api="db,eth,net,engine,rpc,web3"
      --authrpc.jwtsecret="/root/jwt/jwt.hex"
      --authrpc.addr=0.0.0.0
      --authrpc.port=8551
      --authrpc.vhosts="*"
      --metrics
      --metrics.addr=0.0.0.0
      --metrics.port=6060
    volumes:
      - ./data/geth:/root/.ethereum
      - ../../jwt:/root/jwt
    restart: unless-stopped

networks:
  default:
    name: ${CHARON_DOCKER_NETWORK:-compose_development_dvnode}
    external: true