version: "3.8"

services:
  #  _                 _                   _
  # | |__   ___   ___ | |_ _ __   ___   __| | ___
  # | '_ \ / _ \ / _ \| __| '_ \ / _ \ / _` |/ _ \
  # | |_) | (_) | (_) | |_| | | | (_) | (_| |  __/
  # |_.__/ \___/ \___/ \__|_| |_|\___/ \__,_|\___|
  bootnode:
    # Pegged charon version (update this for each release).
    image: obolnetwork/charon:14ce3bf
    environment:
      CHARON_P2P_TCP_ADDRESS: 0.0.0.0:3610
      CHARON_P2P_UDP_ADDRESS: 0.0.0.0:3630
      CHARON_BOOTNODE_HTTP_ADDRESS: 0.0.0.0:3640
      CHARON_LOG_LEVEL: debug
      CHARON_P2P_EXTERNAL_HOSTNAME: replace.with.public.ip.or.hostname
    ports:
      - 3610:3610/tcp
      - 3630:3630/udp
      - 3640:3640/tcp
    command: bootnode
    volumes:
      - .charon:/opt/charon/.charon # Bootnode charon-enr-private-key generated and persisted across restarts in this folder
    restart: on-failure
