# Override any defaults specified by `${FOO:-bar}` in `.env` with `FOO=qux`.
# ${VARIABLE:-default} evaluates to default if VARIABLE is unset or empty in the environment.
# ${VARIABLE-default} evaluates to default only if VARIABLE is unset in the environment.

services:
  #       _
  #   ___| |__   __ _ _ __ ___  _ __
  #  / __| '_ \ / _` | '__/ _ \| '_ \
  # | (__| | | | (_| | | | (_) | | | |
  #  \___|_| |_|\__,_|_|  \___/|_| |_|

  charon:
    image: obolnetwork/charon:${CHARON_VERSION:-v1.0.1}
    environment:
      - CHARON_BEACON_NODE_ENDPOINTS=${CHARON_BEACON_NODE_ENDPOINTS:-http://eth2_bn:5052}
      - CHARON_LOG_LEVEL=${CHARON_LOG_LEVEL:-info}
      - CHARON_LOG_FORMAT=${CHARON_LOG_FORMAT:-console}
      - CHARON_P2P_RELAYS=${CHARON_P2P_RELAYS:-https://0.relay.obol.tech}
      - CHARON_P2P_EXTERNAL_HOSTNAME=${CHARON_P2P_EXTERNAL_HOSTNAME:-} # Empty default required to avoid warnings.
      - CHARON_P2P_TCP_ADDRESS=0.0.0.0:${CHARON_PORT_P2P_TCP:-3610}
      - CHARON_VALIDATOR_API_ADDRESS=0.0.0.0:3600
      - CHARON_MONITORING_ADDRESS=0.0.0.0:3620
      - CHARON_BUILDER_API=${BUILDER_API_ENABLED:-false}
    ports:
      - ${CHARON_PORT_P2P_TCP:-3610}:${CHARON_PORT_P2P_TCP:-3610}/tcp # P2P TCP libp2p
    volumes:
      - ../.charon:/opt/charon/.charon
    restart: unless-stopped
    healthcheck:
      test: wget -qO- http://localhost:3620/readyz
