name: tests
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  create_containers:
    # Ensures default fresh checkout can create containers.
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
    - run: docker compose up --no-start
    - run: docker compose -f docker-compose.yml -f compose-debug.yml up --no-start
